### ISSUE TITLE
requirements.txt required

### ISSUE THREAD

**Issue by IvanAntipov** [sberdevices/golos#1]
The example doesn't work out of the box.

at least 
```
!pip install git+https://github.com/NVIDIA/NeMo.git
!pip install torch_stft
!pip install kaldiio
!pip install frozendict
```
required.

Could you provide the list of requirements in order to install all of them by single command?

**Comment by IvanAntipov** [comment]
In the end, I managed to run the example with the following commands

```
!pip install git+https://github.com/NVIDIA/NeMo.git
!pip install torch_stft
!pip install kaldiio
!pip install frozendict
!pip install inflect
!pip install unidecode
!pip install nemo-toolkit
!pip install nltk
!pip install g2p_en
!pip install editdistance
```

but it can be not the complete list if requirements

**Comment by karpnv** [comment]
Fixed by https://github.com/sberdevices/golos/pull/4
