### ISSUE TITLE
Working example required

### ISSUE THREAD

**Issue by IvanAntipov** [sberdevices/golos#2]
Could you please add an example how to run the model evaluation

a la
```
- example
  |- manifest.json
  |- simple.wav
  |- run.sh
```

Now people like me who haven't worked with Nemo have to infer format of manifest.json from code, to guess do we need to unpack kenlms.tar or not e.t.c., it is not always obvious.

**Comment by karpnv** [comment]
Fixed by https://github.com/sberdevices/golos/pull/4
